#/bin/sh
git pull
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
# java -cp /Library/Java/javaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/javaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/javaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/javaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/javaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/javaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/javaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/javaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/javaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/jacess.jar:/Library/Java/javaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/System/Library/Java/Extensions/MRJToolkit.jar:/Applications/Eclipse.app/Contents/Eclipse/plugins/org.junit_4.12.0.v201504281640/junit.jar:/Applications/Eclipse.app/Contents/Eclipse/plugins/org.hamcrest.core_1.3.0.v20180420-1519.jar:/Users/dan/mokapot-deploy/apache-commons.jar:/Users/dan/mokapot-deploy/javax.jms-api.jar:/Users/dan/mokapot-deploy/slf4j.jar:millr.jar:mokapot.jar:contrib/asm.jar:contrib/asm-analysis.jar:contrib/asm-commons.jar:contrib/asm-util.jar:contrib/asm-tree.jar:contrib/retrolambda.jar xyz.acygn.millr.Mill -i ../deployment -o output\
#java -cp /Library/Java/javaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/javaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/javaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/javaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/javaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/javaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/javaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/javaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/javaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/jacess.jar:/Library/Java/javaVirtualMachinmillr.jar:mokapot.jar:contrib/asm.jar:contrib/asm-analysis.jar:contrib/asm-commons.jar:contrib/asm-util.jar:contrib/asm-tree.jar:contrib/retrolambda.jar xyz.acygn.millr.Mill -i ../git -o output
#ant run-millr -Dinput=../deploymentOriginal -Doutput=../deployment
#mv ~/deployment/deploymentOriginal/* ~/deployment
mkdir ../deployment/TEL_Server\ Rel.5/lib/
cp millr.jar mokapot.jar whitelist.jar ../deployment/TEL_Server\ Rel.5/lib/
cd ../git/Tel_Server/
ant -lib ../Utilities/lib_ant/  deploy_milled_project
